### ISSUE TITLE
hurl + github auth

### ISSUE THREAD

**Issue by korjik** [defunkt/hurl#44]
Hey bro! 

U've done a great product but I receive 500 when auth with github.

These are my nginx logs:

```
NameError - uninitialized constant Hurl::App::User:
 /home/applications/hurl/app/app.rb:45:in `block in <class:App>'
 /usr/local/lib/ruby/gems/1.9.1/gems/sinatra-1.1.0/lib/sinatra/base.rb:596:in `instance_eval'
 /usr/local/lib/ruby/gems/1.9.1/gems/sinatra-1.1.0/lib/sinatra/base.rb:596:in `block in filter!'
 /usr/local/lib/ruby/gems/1.9.1/gems/sinatra-1.1.0/lib/sinatra/base.rb:596:in `each'
 /usr/local/lib/ruby/gems/1.9.1/gems/sinatra-1.1.0/lib/sinatra/base.rb:596:in `filter!'
 /usr/local/lib/ruby/gems/1.9.1/gems/sinatra-1.1.0/lib/sinatra/base.rb:740:in `dispatch!'
 /usr/local/lib/ruby/gems/1.9.1/gems/sinatra-1.1.0/lib/sinatra/base.rb:530:in `block in call!'
 /usr/local/lib/ruby/gems/1.9.1/gems/sinatra-1.1.0/lib/sinatra/base.rb:706:in `instance_eval'
 /usr/local/lib/ruby/gems/1.9.1/gems/sinatra-1.1.0/lib/sinatra/base.rb:706:in `block in invoke'
 /usr/local/lib/ruby/gems/1.9.1/gems/sinatra-1.1.0/lib/sinatra/base.rb:706:in `catch'
 /usr/local/lib/ruby/gems/1.9.1/gems/sinatra-1.1.0/lib/sinatra/base.rb:706:in `invoke'
 /usr/local/lib/ruby/gems/1.9.1/gems/sinatra-1.1.0/lib/sinatra/base.rb:530:in `call!'
 /usr/local/lib/ruby/gems/1.9.1/gems/sinatra-1.1.0/lib/sinatra/base.rb:516:in `call'
 /usr/local/lib/ruby/gems/1.9.1/gems/warden-0.10.7/lib/warden/manager.rb:35:in `block in call'
 /usr/local/lib/ruby/gems/1.9.1/gems/warden-0.10.7/lib/warden/manager.rb:34:in `catch'
 /usr/local/lib/ruby/gems/1.9.1/gems/warden-0.10.7/lib/warden/manager.rb:34:in `call'
 /usr/local/lib/ruby/gems/1.9.1/gems/rack-1.2.1/lib/rack/session/cookie.rb:37:in `call'
 /usr/local/lib/ruby/gems/1.9.1/gems/passenger-3.0.2/lib/phusion_passenger/rack/request_handler.rb:96:in `process_request'
 /usr/local/lib/ruby/gems/1.9.1/gems/passenger-3.0.2/lib/phusion_passenger/abstract_request_handler.rb:513:in `accept_and_process_next_request'
 /usr/local/lib/ruby/gems/1.9.1/gems/passenger-3.0.2/lib/phusion_passenger/abstract_request_handler.rb:274:in `main_loop'
 /usr/local/lib/ruby/gems/1.9.1/gems/passenger-3.0.2/lib/phusion_passenger/rack/application_spawner.rb:205:in `start_request_handler'
 /usr/local/lib/ruby/gems/1.9.1/gems/passenger-3.0.2/lib/phusion_passenger/rack/application_spawner.rb:170:in `block in handle_spawn_application'
 /usr/local/lib/ruby/gems/1.9.1/gems/passenger-3.0.2/lib/phusion_passenger/utils.rb:479:in `safe_fork'
 /usr/local/lib/ruby/gems/1.9.1/gems/passenger-3.0.2/lib/phusion_passenger/rack/application_spawner.rb:165:in `handle_spawn_application'
 /usr/local/lib/ruby/gems/1.9.1/gems/passenger-3.0.2/lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
 /usr/local/lib/ruby/gems/1.9.1/gems/passenger-3.0.2/lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
 /usr/local/lib/ruby/gems/1.9.1/gems/passenger-3.0.2/lib/phusion_passenger/abstract_server.rb:180:in `start'
 /usr/local/lib/ruby/gems/1.9.1/gems/passenger-3.0.2/lib/phusion_passenger/rack/application_spawner.rb:128:in `start'
 /usr/local/lib/ruby/gems/1.9.1/gems/passenger-3.0.2/lib/phusion_passenger/spawn_manager.rb:253:in `block (2 levels) in spawn_rack_application'
 /usr/local/lib/ruby/gems/1.9.1/gems/passenger-3.0.2/lib/phusion_passenger/abstract_server_collection.rb:132:in `lookup_or_add'
 /usr/local/lib/ruby/gems/1.9.1/gems/passenger-3.0.2/lib/phusion_passenger/spawn_manager.rb:246:in `block in spawn_rack_application'
 /usr/local/lib/ruby/gems/1.9.1/gems/passenger-3.0.2/lib/phusion_passenger/abstract_server_collection.rb:82:in `block in synchronize'
 <internal:prelude>:8:in `synchronize'
 /usr/local/lib/ruby/gems/1.9.1/gems/passenger-3.0.2/lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
 /usr/local/lib/ruby/gems/1.9.1/gems/passenger-3.0.2/lib/phusion_passenger/spawn_manager.rb:244:in `spawn_rack_application'
 /usr/local/lib/ruby/gems/1.9.1/gems/passenger-3.0.2/lib/phusion_passenger/spawn_manager.rb:137:in `spawn_application'
 /usr/local/lib/ruby/gems/1.9.1/gems/passenger-3.0.2/lib/phusion_passenger/spawn_manager.rb:275:in `handle_spawn_application'
 /usr/local/lib/ruby/gems/1.9.1/gems/passenger-3.0.2/lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
 /usr/local/lib/ruby/gems/1.9.1/gems/passenger-3.0.2/lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
 /usr/local/lib/ruby/gems/1.9.1/gems/passenger-3.0.2/helper-scripts/passenger-spawn-server:99:in `<main>'
No view class found for 500 in /home/applications/hurl/app/views

```

**Comment by korjik** [comment]
This issue is fixed by raptor-sc by modifying 45th string of app.rb:

@user = Hurl::User.new(github_user)
